# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kacper/programowanie/CPP/Tamandua

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kacper/programowanie/CPP/Tamandua

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kacper/programowanie/CPP/Tamandua/CMakeFiles /home/kacper/programowanie/CPP/Tamandua/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kacper/programowanie/CPP/Tamandua/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tamandua

# Build rule for target.
tamandua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tamandua
.PHONY : tamandua

# fast build rule for target.
tamandua/fast:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/build
.PHONY : tamandua/fast

src/client.o: src/client.cpp.o
.PHONY : src/client.o

# target to build an object file
src/client.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/client.cpp.o
.PHONY : src/client.cpp.o

src/client.i: src/client.cpp.i
.PHONY : src/client.i

# target to preprocess a source file
src/client.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/client.cpp.i
.PHONY : src/client.cpp.i

src/client.s: src/client.cpp.s
.PHONY : src/client.s

# target to generate assembly for a file
src/client.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/client.cpp.s
.PHONY : src/client.cpp.s

src/group.o: src/group.cpp.o
.PHONY : src/group.o

# target to build an object file
src/group.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/group.cpp.o
.PHONY : src/group.cpp.o

src/group.i: src/group.cpp.i
.PHONY : src/group.i

# target to preprocess a source file
src/group.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/group.cpp.i
.PHONY : src/group.cpp.i

src/group.s: src/group.cpp.s
.PHONY : src/group.s

# target to generate assembly for a file
src/group.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/group.cpp.s
.PHONY : src/group.cpp.s

src/hidden_participant.o: src/hidden_participant.cpp.o
.PHONY : src/hidden_participant.o

# target to build an object file
src/hidden_participant.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/hidden_participant.cpp.o
.PHONY : src/hidden_participant.cpp.o

src/hidden_participant.i: src/hidden_participant.cpp.i
.PHONY : src/hidden_participant.i

# target to preprocess a source file
src/hidden_participant.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/hidden_participant.cpp.i
.PHONY : src/hidden_participant.cpp.i

src/hidden_participant.s: src/hidden_participant.cpp.s
.PHONY : src/hidden_participant.s

# target to generate assembly for a file
src/hidden_participant.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/hidden_participant.cpp.s
.PHONY : src/hidden_participant.cpp.s

src/message_buffer.o: src/message_buffer.cpp.o
.PHONY : src/message_buffer.o

# target to build an object file
src/message_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/message_buffer.cpp.o
.PHONY : src/message_buffer.cpp.o

src/message_buffer.i: src/message_buffer.cpp.i
.PHONY : src/message_buffer.i

# target to preprocess a source file
src/message_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/message_buffer.cpp.i
.PHONY : src/message_buffer.cpp.i

src/message_buffer.s: src/message_buffer.cpp.s
.PHONY : src/message_buffer.s

# target to generate assembly for a file
src/message_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/message_buffer.cpp.s
.PHONY : src/message_buffer.cpp.s

src/message_composer.o: src/message_composer.cpp.o
.PHONY : src/message_composer.o

# target to build an object file
src/message_composer.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/message_composer.cpp.o
.PHONY : src/message_composer.cpp.o

src/message_composer.i: src/message_composer.cpp.i
.PHONY : src/message_composer.i

# target to preprocess a source file
src/message_composer.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/message_composer.cpp.i
.PHONY : src/message_composer.cpp.i

src/message_composer.s: src/message_composer.cpp.s
.PHONY : src/message_composer.s

# target to generate assembly for a file
src/message_composer.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/message_composer.cpp.s
.PHONY : src/message_composer.cpp.s

src/participant.o: src/participant.cpp.o
.PHONY : src/participant.o

# target to build an object file
src/participant.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/participant.cpp.o
.PHONY : src/participant.cpp.o

src/participant.i: src/participant.cpp.i
.PHONY : src/participant.i

# target to preprocess a source file
src/participant.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/participant.cpp.i
.PHONY : src/participant.cpp.i

src/participant.s: src/participant.cpp.s
.PHONY : src/participant.s

# target to generate assembly for a file
src/participant.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/participant.cpp.s
.PHONY : src/participant.cpp.s

src/private_room.o: src/private_room.cpp.o
.PHONY : src/private_room.o

# target to build an object file
src/private_room.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/private_room.cpp.o
.PHONY : src/private_room.cpp.o

src/private_room.i: src/private_room.cpp.i
.PHONY : src/private_room.i

# target to preprocess a source file
src/private_room.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/private_room.cpp.i
.PHONY : src/private_room.cpp.i

src/private_room.s: src/private_room.cpp.s
.PHONY : src/private_room.s

# target to generate assembly for a file
src/private_room.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/private_room.cpp.s
.PHONY : src/private_room.cpp.s

src/room.o: src/room.cpp.o
.PHONY : src/room.o

# target to build an object file
src/room.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/room.cpp.o
.PHONY : src/room.cpp.o

src/room.i: src/room.cpp.i
.PHONY : src/room.i

# target to preprocess a source file
src/room.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/room.cpp.i
.PHONY : src/room.cpp.i

src/room.s: src/room.cpp.s
.PHONY : src/room.s

# target to generate assembly for a file
src/room.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/room.cpp.s
.PHONY : src/room.cpp.s

src/root.o: src/root.cpp.o
.PHONY : src/root.o

# target to build an object file
src/root.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/root.cpp.o
.PHONY : src/root.cpp.o

src/root.i: src/root.cpp.i
.PHONY : src/root.i

# target to preprocess a source file
src/root.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/root.cpp.i
.PHONY : src/root.cpp.i

src/root.s: src/root.cpp.s
.PHONY : src/root.s

# target to generate assembly for a file
src/root.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/root.cpp.s
.PHONY : src/root.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/user.o: src/user.cpp.o
.PHONY : src/user.o

# target to build an object file
src/user.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/user.cpp.o
.PHONY : src/user.cpp.o

src/user.i: src/user.cpp.i
.PHONY : src/user.i

# target to preprocess a source file
src/user.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/user.cpp.i
.PHONY : src/user.cpp.i

src/user.s: src/user.cpp.s
.PHONY : src/user.s

# target to generate assembly for a file
src/user.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/user.cpp.s
.PHONY : src/user.cpp.s

src/user_message_interpreter.o: src/user_message_interpreter.cpp.o
.PHONY : src/user_message_interpreter.o

# target to build an object file
src/user_message_interpreter.cpp.o:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/user_message_interpreter.cpp.o
.PHONY : src/user_message_interpreter.cpp.o

src/user_message_interpreter.i: src/user_message_interpreter.cpp.i
.PHONY : src/user_message_interpreter.i

# target to preprocess a source file
src/user_message_interpreter.cpp.i:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/user_message_interpreter.cpp.i
.PHONY : src/user_message_interpreter.cpp.i

src/user_message_interpreter.s: src/user_message_interpreter.cpp.s
.PHONY : src/user_message_interpreter.s

# target to generate assembly for a file
src/user_message_interpreter.cpp.s:
	$(MAKE) -f CMakeFiles/tamandua.dir/build.make CMakeFiles/tamandua.dir/src/user_message_interpreter.cpp.s
.PHONY : src/user_message_interpreter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tamandua"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/group.o"
	@echo "... src/group.i"
	@echo "... src/group.s"
	@echo "... src/hidden_participant.o"
	@echo "... src/hidden_participant.i"
	@echo "... src/hidden_participant.s"
	@echo "... src/message_buffer.o"
	@echo "... src/message_buffer.i"
	@echo "... src/message_buffer.s"
	@echo "... src/message_composer.o"
	@echo "... src/message_composer.i"
	@echo "... src/message_composer.s"
	@echo "... src/participant.o"
	@echo "... src/participant.i"
	@echo "... src/participant.s"
	@echo "... src/private_room.o"
	@echo "... src/private_room.i"
	@echo "... src/private_room.s"
	@echo "... src/room.o"
	@echo "... src/room.i"
	@echo "... src/room.s"
	@echo "... src/root.o"
	@echo "... src/root.i"
	@echo "... src/root.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/user.o"
	@echo "... src/user.i"
	@echo "... src/user.s"
	@echo "... src/user_message_interpreter.o"
	@echo "... src/user_message_interpreter.i"
	@echo "... src/user_message_interpreter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

