#define TAMANDUA_VERSION_MAJOR @Tamandua_VERSION_MAJOR@
#define TAMANDUA_VERSION_MINOR @Tamandua_VERSION_MINOR@
#define TAMANDUA_VERSION_PATCH @Tamandua_VERSION_PATCH@
#define TAMANDUA_RELEASE_TYPE "@Tamandua_RELEASE_TYPE@"
